
variable "client_id" {
   default =   env("ARM_CLIENT_ID")
}
variable "subscription_id" {
   default =   env("ARM_SUBSCRIPTION_ID")
}
variable "client_secret" {
   default =   env("ARM_CLIENT_SECRET")
}
variable "tenant_id" {
   default =   env("ARM_TENANT_ID")
}
variable "location" {
    type = string
    default = "East US"
}
variable "managed_image_name" {
    type = string
    default = "RedHat-8.4"
}
variable "managed_image_resource_group_name" {
    type = string
    default = "myPackerImages"
}
variable "vm_size" {
    type = string
    default = "Standard_D2as_v4"
}
source "azure-arm" "autogenerated_1" {

  client_id                         = var.client_id
  client_secret                     = var.client_secret
  subscription_id                   = var.subscription_id
  tenant_id                         = var.tenant_id
  image_offer                       = "RHEL"
  image_publisher                   = "RedHat"
  image_sku                         = "86-gen2"
  location                          = var.location
  managed_image_name                = var.managed_image_name
  managed_image_resource_group_name = var.managed_image_resource_group_name
  os_type                           = "Linux"
  vm_size                           = var.vm_size
}

build {
  sources = ["source.azure-arm.autogenerated_1"]
  
}
